apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openst-tile-pv-claim
  labels:
    app: openst-tile
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openst-tile-config
  labels:
    app: openst-tile
data:
  PGHOST: 
  PGUSER:
  PGPASSWORD: 

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openst-tile
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openst-tile
    spec:
      containers:
        - name: openst-tile
          image: danghung/openst:kosmtik
          imagePullPolicy: "Always"
          ports:
            - containerPort: 6789
          envFrom:
            - configMapRef:
                name: openst-tile-config
          volumeMounts:
            - mountPath: /openstreetmap-carto
              name: openstreetmap
      volumes:
        - name: openstreetmap
          persistentVolumeClaim:
            claimName: openst-tile-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: openst-tile
  labels:
    app: openst-tile
spec:
  selector:
    app: openst-tile
  ports:
    - port: 6789
      protocol: TCP
      targetPort: 6789
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openst-tile
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: kb-openst.danghung.xyz
      http:
        paths:
          - path: /
            backend:
              serviceName: openst-tile
              servicePort: 6789