apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nominatim-pv-claim
  namespace: openst
  labels:
    app: osm-nominatim
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---      
apiVersion: v1
kind: Service
metadata:
  name: nominatim
  namespace: openst
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: nominatim
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nominatim
  namespace: openst
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nominatim
        track: stable
    spec:
      volumes:
        - name: osm-nominatim-volume
          persistentVolumeClaim:
            claimName: nominatim-pv-claim
      containers:
      - name: nominatim-k8s
        image: danghung/osm-nominatim:latest
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /var/lib/postgresql/11/main
            name: osm-nominatim-volume
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /search
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nominatim
  namespace: openst
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: nominatim.danghung.xyz
      http:
        paths:
          - path: /
            backend:
              serviceName: nominatim
              servicePort: 80