apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: osm-tiles-server
  namespace: openst
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: osm-tiles-server
    spec:
      containers:
        - name: osm-tiles-server
          image: overv/openstreetmap-tile-server
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          args: ["run"]
          # command:
          #   - run
          volumeMounts:
            - mountPath: /var/lib/mod_tile
              name: osm-mod-tile
      volumes:
        - name: osm-mod-tile
          persistentVolumeClaim:
            claimName: osm-tiles-server-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: osm-tiles-server
  namespace: openst
  labels:
    app: osm-tiles-server
spec:
  selector:
    app: osm-tiles-server
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: osm-tiles-server
  namespace: openst
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: osm-tiles.danghung.xyz
      http:
        paths:
          - path: /
            backend:
              serviceName: osm-tiles-server
              servicePort: 80
